import turtle as t
t1 = t.Turtle()
s = t.Screen()
t.speed('fastest')
colors = ['gray', '#5C4033', 'black', 'white', 'yellow', '#6F8FAF']

t.penup()
t.pendown()
t.pencolor('yellow')
t.begin_fill()
t.fillcolor('yellow')
t.circle(150)
t.end_fill()

t.penup()
t.right(90)
t.forward(200)
t.left(90)
t.pendown()
t.pencolor('#6F8FAF')
t.begin_fill()
t.fillcolor('#6F8FAF')
t.circle(150)
t.end_fill()

t.penup()
t.forward(150)
t.left(90)
t.forward(350)
t.begin_fill()
t.fillcolor('yellow')
t.left(90)
t.forward(300)
t.left(90)
t.forward(220)
t.left(90)
t.forward(300)
t.end_fill()

t.penup()
t.backward(60)
t.left(90)
t.pendown()
t.begin_fill()
t.fillcolor('#6F8FAF')
t.forward(120)
t.left(90)
t.forward(180)
t.left(90)
t.forward(120)
t.left(90)
t.forward(180)
t.end_fill()

# t.penup()
# t.pencolor('black')
# t.left(90)
# t.forward(110)
# t.left(90)
# t.forward(20)
# t.pendown()
# t.circle(10)

# t.penup()
# t.forward(140)
# t.pendown()
# t.circle(10)
t.penup()
t.left(90)
t.forward(120)
t.left(90)
t.forward(10)
t.right(90)
t.pencolor("#2D4052")
t.begin_fill()
t.fillcolor("#6F8FAF")
t.pendown()
t.right(55)
t.forward(85)
t.right(125)
t.forward(40)
t.right(55)
t.forward(110)
t.right(125)
t.forward(40)
t.right(55)
t.forward(25)
t.end_fill()

t.penup()
t.left(145)
t.forward(160)
t.begin_fill()
t.fillcolor("#6F8FAF")
t.pendown()
t.right(35)
t.forward(85)
t.left(125)
t.forward(40)
t.left(55)
t.forward(110)
t.left(125)
t.forward(40)
t.left(55)
t.forward(25)
t.end_fill()

t.penup()
t.forward(8)
t.left(125)
t.forward(28)
t.begin_fill()
t.fillcolor("#2D4052")
t.pendown()
t.pencolor('black')
t.circle(10)
t.end_fill()

t.penup()
t.left(90)
t.forward(164)
t.right(90)
t.forward(10)
t.left(90)
t.begin_fill()
t.fillcolor("#2D4052")
t.pendown()
t.circle(10)
t.end_fill()

t.penup()
t.backward(77)
t.left(90)
t.forward(150)
t.right(90)
t.forward(80)
t.left(90)

# t.hideturtle()
t.begin_fill()
t.fillcolor("#FFFFFF")
t.pendown()
t.pencolor('gray')
t.width(20)
t.circle(80)
t.end_fill()

t.penup()
t.left(90)
t.forward(60)
t.right(90)
t.pencolor('black')
t.width(1)
t.begin_fill()
t.fillcolor('#5C4033')
t.pendown()
t.circle(40)
t.end_fill()

t.penup()
t.left(90)
t.forward(20)
t.right(90)
t.pencolor('black')
t.width(1)
t.begin_fill()
t.fillcolor('black')
t.pendown()
t.circle(20)
t.end_fill()

t.penup()
t.left(180)
t.backward(15)
t.right(90)
t.forward(25)
t.right(90)
t.pencolor('white')
t.width(1)
t.begin_fill()
t.fillcolor('white')
t.pendown()
t.circle(8)
t.end_fill()

t.penup()
t.right(90)
t.forward(175)
t.right(90)
t.forward(140)
t.left(35)
t.pendown()
t.pencolor('yellow')
t.begin_fill()
t.fillcolor('yellow')
t.forward(100)
t.right(80)
t.forward(30)
t.right(100)
t.forward(70)
t.end_fill()

t.penup()
t.backward(90)
t.pencolor('black')
t.right(125)
t.forward(8)
t.pendown()
t.begin_fill()
t.fillcolor('black')
t.circle(20)
t.end_fill()
t.backward(10)
t.right(90)
t.forward(5)
t.begin_fill()
t.circle(8)
t.end_fill()
t.penup()
t.forward(5)
t.left(90)
t.forward(22)
t.pendown()
t.begin_fill()
t.circle(8)
t.end_fill()
t.penup()
t.left(90)
t.forward(12)
t.right(90)
t.forward(10)
t.pendown()
t.begin_fill()
t.circle(8)
t.end_fill()

t.penup()
t.left(90)
t.forward(120)
t.left(90)
t.forward(380)
t.left(55)
t.pendown()
t.pencolor('yellow')
t.begin_fill()
t.fillcolor('yellow')
t.forward(120)
t.left(80)
t.forward(30)
t.left(100)
t.forward(90)
t.end_fill()

t.penup()
t.backward(90)
t.right(35)
t.forward(5)
t.pencolor('black')
t.pendown()
t.begin_fill()
t.fillcolor('black')
t.circle(20)
t.end_fill()

t.penup()
t.forward(5)
t.right(90)
t.forward(5)
t.left(180)
t.pendown()
t.begin_fill()
t.circle(8)
t.end_fill()
t.penup()
t.left(90)
t.forward(18)
t.right(110)
t.forward(5)
t.pendown()
t.begin_fill()
t.circle(8)
t.end_fill()
t.penup()
t.left(90)
t.forward(12)
t.right(90)
t.forward(10)
t.pendown()
t.begin_fill()
t.circle(8)
t.end_fill()

t.penup()
t.right(90)
t.forward(125)
t.right(90)
t.forward(120)
t.pendown()
t.begin_fill()
t.circle(45)
t.end_fill()
t.penup()
t.left(90)
t.forward(90)
t.right(90)
t.pendown()
t.begin_fill()
t.circle(45)
t.end_fill()

t.penup()
t.pencolor('white')
t.fillcolor('white')
t.right(90)
t.forward(90)
t.left(90)
t.begin_fill()
t.forward(50)
t.left(90)
t.forward(180)
t.left(90)
t.forward(50)
t.left(90)
t.forward(180)
t.end_fill()

t.hideturtle()
t.done()
